### ISSUE TITLE
Error when  "oidc_login_disable_registration" is set to "true"

### ISSUE THREAD

**Issue by buekera** [pulsejet/nextcloud-oidc-login#14]
Hi there!

I like your plugin/addon so far. I am using it with keycloak as identity provider and followed your setup guide step by step. Both keycloak and nextcloud are running within my docker swarm but I did not notice any strange behavior other than the below.

I noticed that the login is failing without any errors shown when setting _oidc_login_disable_registration_ to _true_ as suggested by yourself. When printing the error with PHP the following shows up:  **Auto creating new users is disabled**. This error is thrown in the LoginController when adding an echo in the catch block beginning at line 88.

Now when I set it to _false_ it works fine and I'm logged in correctly and the user is, as expected, created in my nextcloud. I don't know if you just forgot to mention that you have to enable _oidc_login_disable_registration_ in order for this to work or if I doing something wrong here.

Thanks in advance for your time

**Comment by pulsejet** [comment]
Hi! It is by design that `oidc_login_disable_registration` defaults to `true`, since you do not want to rely on a third party for user creation without configuring it explicitly. The same is mentioned in the readme.

Thanks!

**Comment by buekera** [comment]
Ah I see... In my case the users do not exist within nextcloud so I have to set it to _false_. That's completely fine for me 👍

**Comment by r2evans** [comment]
*No need to reopen this issue, I wanted to add some context that would have helped me to more-quickly pinpoint this issue as applicable to my situation. I was about to file a new issue (ergo this is full of details) when I gave this issue another look-over.*

A suggestion (for thought): is there a way to notify the user that this occurred? It is far more informative to say to the admin "Error 1234: user not created" than "nothing happened".

My symptoms: OpenID process went without error, no authentication, just an uninformed return to the login screen.

Ultimately, authentication to the realm was successful, but nextcloud kept returning to the login screen without an apparent error.

My basic configuration, much of it provided as ancillary (unrelated) information:

- stack is running on a synology (DS6) NAS, with only 443 port-forwarded from my internet connection
- A docker stack with `traefik:2.3.6`, `jboss/keycloak:12.0.1`, and `nextcloud:19.0.3-apache`
- traefik is configured as an SSL terminator, with nextcloud among other (unrelated) services, so nextcloud is reached via http behind the scenes
- keycloak is configured properly with a realm `myrealm` and a user `rtwo` within that realm
- `my.domain.com` is internet facing with a valid LetsEncrypt SSL certificate
- with the single hostname, I have multiple services as sub-dirs; keycloak is available under `my.domain.com/auth/`, nextcloud as `my.domain.com/cloud/`
- (and all of this is currently throw-away within "play" docker containers, so any secrets I may not have scrubbed sufficiently are ephemeral)

## Bottom Line Up Front

Change `oidc_login_disable_registration` in my `oidc.config.php` to true.

```php
    'oidc_login_disable_registration' => true,
```

Ultimately, when I'm confident that all OpenID-based users have been "seen" by nextcloud, I will likely set this back to false. I don't know if there are security implications associated with this.

## Config

(Before the fix.)

<details><summary> <code>docker-compose.yml</code> </summary>

```yml
version: '3.7'
services:
  traefik:
    image: traefik:2.3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/dynamic"
    ports:
      - "443:443"
      - "8081:8080" # webui
    volumes:
      - /run/docker.sock:/var/run/docker.sock:ro
      - /volume1/docker/mystack/ssl:/certs:ro
      - ./assets/traefik_config.yml:/etc/traefik/dynamic/config.yml:ro
    labels:
      - "traefik.tls.options.default.sniStrict=true"
      - "traefik.tls.options.default.minVersion=VersionTLS12"
      - "traefik.http.middlewares.default-headers.SSLRedirect=true"
      - "traefik.http.middlewares.default-headers.STSSeconds=315360000"
      - "traefik.http.middlewares.default-headers.forceSTSHeader=true"
      - "traefik.http.middlewares.default-headers.stsIncludeSubdomains=true"
  postgres:
    image: postgres:11.10
    ports:
      - "15432:5432"
    volumes:
      - /volume1/docker/mystack/pg/data:/var/lib/postgresql/data
      - ./assets/postgres-initdb.d:/docker-entrypoint-initdb.d:ro
    secrets:
      - pg_admin_password
  keycloak:
    image: jboss/keycloak:12.0.1
    secrets:
      - kc_pg_password
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=kcdb
      - DB_USER=kcuser
      - DB_SCHEMA=public
      - DB_PASSWORD_FILE=/run/secrets/kc_pg_password
      ## from https://keycloak.discourse.group/t/blank-admin-console/2026
      - PROXY_ADDRESS_FORWARDING=true 
    depends_on:
      - postgres
    ports:
      - "8443:8443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.rule=PathPrefix(`/auth`)"
  nextcloud:
    image: nextcloud:19.0.3-apache
    depends_on:
      - postgres
      - traefik
    volumes:
      - /volume1/docker/mystack/nc/config:/var/www/html/config
      - /volume1/docker/mystack/nc/data:/data
      - /volume1/docker/mystack/nc/custom_apps:/var/www/html/custom_apps
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=PathPrefix(`/cloud`)"
      - "traefik.http.routers.nextcloud.middlewares=nc-stripprefix"
      - "traefik.http.middlewares.nc-stripprefix.stripprefix.prefixes=/cloud"
```

</details>

<details><summary> <code>nextcloud/config/oidc.config.php</code> </summary>

```
<?php
$CONFIG = array (
    'allow_user_to_change_display_name' => false,
    'lost_password_link' => 'disabled',
    'oidc_login_provider_url' => 'https://my.domain.com/auth/realms/myrealm',
    'oidc_login_client_id' => 'nas1-nextcloud',
    'oidc_login_client_secret' => '...',
    'oidc_login_auto_redirect' => true,
    'oidc_login_logout_url' => 'https://my.domain.com/auth/realms/myrealm/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Fmy.domain.com%2Fcloud',
    'oidc_login_default_quota' => '1000000000',
    'oidc_login_button_text' => 'Log in with OpenID (myrealm)',
    'oidc_login_hide_password_form' => false,
    'oidc_login_attributes' => array (
        'id' => 'preferred_username',
        'mail' => 'email',
    ),
    'oidc_login_default_group' => 'oidc',
    'oidc_login_use_external_storage' => false,
    'oidc_login_scope' => 'openid profile',
    'oidc_login_proxy_ldap' => false,
    'oidc_login_disable_registration' => true,
    'oidc_login_redir_fallback' => true,
    'oidc_login_alt_login_page' => 'assets/login.php',
    'oidc_login_tls_verify' => true,
);
```

</details>

## Logs

<details><summary> Docker (nextcloud) logs </summary>

```
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:36 +0000] \"GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1\" 304 190 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:36.351443183Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:36 +0000] \"GET / HTTP/1.1\" 302 1463 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:36.882564679Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:36 +0000] \"GET /index.php/login HTTP/1.1\" 302 897 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:36.98770106Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:37 +0000] \"GET /index.php/apps/oidc_login/oidc HTTP/1.1\" 302 1175 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:37.146138552Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:41 +0000] \"GET /index.php/apps/oidc_login/oidc?state=51fd9f8fd5483e8c831916b8846c659a\u0026session_state=c5d4065d-df1f-4320-b2ea-c3c4fd9bb861\u0026code=b9fcac41-2ff9-42af-b41e-dee78f9cfa24.c5d4065d-df1f-4320-b2ea-c3c4fd9bb861.5320b6e3-7ebd-4014-9363-4f8d3873365c HTTP/1.1\" 302 918 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:41.615731868Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:41 +0000] \"GET /index.php/login?noredir=1 HTTP/1.1\" 200 4915 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:41.770891356Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:41 +0000] \"GET /core/css/guest.css?v=41fc57ba-0 HTTP/1.1\" 200 6058 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:41.921238002Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:41 +0000] \"GET /apps/files_sharing/js/dist/main.js?v=41fc57ba-0 HTTP/1.1\" 200 1130 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:41.927310835Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:41 +0000] \"GET /core/search/js/search.js?v=41fc57ba-0 HTTP/1.1\" 200 2179 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:41.927773896Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:41 +0000] \"GET /apps/files_videoplayer/js/main.js?v=41fc57ba-0 HTTP/1.1\" 200 3207 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:41.92836639Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/js/files/fileinfo.js?v=41fc57ba-0 HTTP/1.1\" 200 1424 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.017403063Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/js/files/client.js?v=41fc57ba-0 HTTP/1.1\" 200 6223 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.017876027Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/search/js/searchprovider.js?v=41fc57ba-0 HTTP/1.1\" 200 4245 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.018211906Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:41 +0000] \"GET /index.php/js/core/merged-template-prepend.js?v=41fc57ba-0 HTTP/1.1\" 200 3856 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.027315723Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:41 +0000] \"GET /core/js/dist/main.js?v=41fc57ba-0 HTTP/1.1\" 200 425706 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.051602286Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/js/dist/login.js?v=41fc57ba-0 HTTP/1.1\" 200 238298 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.089144861Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:41 +0000] \"GET /index.php/apps/theming/styles?v=0 HTTP/1.1\" 200 1377 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.125973707Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /index.php/apps/theming/js/theming?v=0 HTTP/1.1\" 200 994 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.13214557Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /index.php/apps/accessibility/js/accessibility?v=0 HTTP/1.1\" 200 846 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.172590225Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/img/background.png?v=0 HTTP/1.1\" 200 35807 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.224357641Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /index.php/svg/core/logo/logo?color=fff\u0026v=1 HTTP/1.1\" 200 1063 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.315081707Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/img/loading-dark.gif HTTP/1.1\" 200 5161 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.574517348Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/img/actions/toggle.svg HTTP/1.1\" 200 788 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.574602396Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/img/actions/confirm-white.svg?v=2 HTTP/1.1\" 200 885 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.57462022Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/img/favicon.ico HTTP/1.1\" 200 3721 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.630294427Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/img/favicon-touch.png HTTP/1.1\" 200 3362 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:42.630360343Z"}
{"log":"192.168.0.3 - - [09/Jan/2021:16:28:42 +0000] \"GET /core/js/dist/main.js.map HTTP/1.1\" 200 1362162 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"\n","stream":"stdout","time":"2021-01-09T16:28:43.032272769Z"}
```

</details>

And from my browser debug console network trace, the first three queries. Each query contains the "fetch" metadata, and the full request headers and response headers. (Most of it is ancillary, mostly provided as a troubleshooting step I took. My apologies for the noise.)

<details><summary> <code>/auth/realms/myrealm/login-actions/authenticate</code> </summary>

```
await fetch("https://my.domain.com/auth/realms/myrealm/login-actions/authenticate?session_code=-zpeUBQ12IcymAU8UzVSG59Q8hoH4k2TCsLQ-R22mzc&execution=68dbf4b7-a8df-41d3-bbbe-e01aa0938b31&client_id=nas1-nextcloud&tab_id=4sdJ-gdDl-g", {
    "credentials": "include",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Content-Type": "application/x-www-form-urlencoded",
        "Upgrade-Insecure-Requests": "1",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    },
    "body": "username=rtwo&password=...&credentialId=",
    "method": "POST",
    "mode": "cors"
});

POST /auth/realms/myrealm/login-actions/authenticate?session_code=-zpeUBQ12IcymAU8UzVSG59Q8hoH4k2TCsLQ-R22mzc&execution=68dbf4b7-a8df-41d3-bbbe-e01aa0938b31&client_id=nas1-nextcloud&tab_id=4sdJ-gdDl-g HTTP/1.1
Host: my.domain.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
Content-Length: 44
Origin: null
DNT: 1
Connection: keep-alive
Cookie: AUTH_SESSION_ID=c5d4065d-df1f-4320-b2ea-c3c4fd9bb861.29f9a0b34f1f; AUTH_SESSION_ID_LEGACY=c5d4065d-df1f-4320-b2ea-c3c4fd9bb861.29f9a0b34f1f; KC_RESTART=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzY2EzNGNkMC05MTVmLTQzMjItYmIzZi1mYjdkZjllZDQ2NmYifQ.eyJjaWQiOiJuYXMxLW5leHRjbG91ZCIsInB0eSI6Im9wZW5pZC1jb25uZWN0IiwicnVyaSI6Imh0dHBzOi8vb2MuOHBhd2V4cHJlc3MuY29tL29jL2luZGV4LnBocC9hcHBzL29pZGNfbG9naW4vb2lkYyIsImFjdCI6IkFVVEhFTlRJQ0FURSIsIm5vdGVzIjp7InNjb3BlIjoib3BlbmlkIHByb2ZpbGUgb3BlbmlkIiwiaXNzIjoiaHR0cHM6Ly9vYy44cGF3ZXhwcmVzcy5jb20vYXV0aC9yZWFsbXMvOHBhdyIsInJlc3BvbnNlX3R5cGUiOiJjb2RlIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6Ly9vYy44cGF3ZXhwcmVzcy5jb20vb2MvaW5kZXgucGhwL2FwcHMvb2lkY19sb2dpbi9vaWRjIiwic3RhdGUiOiI1MWZkOWY4ZmQ1NDgzZThjODMxOTE2Yjg4NDZjNjU5YSIsIm5vbmNlIjoiMmMzZjM1NjQ0YWQ5Zjk1ZmQ1MDJhNTU4MzdiODA2MDMifX0.lrlFOFyRn9we-yl6N95zI-2CSd0Kfx4GFFRetWuioWw
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache

HTTP/2 302 Found
cache-control: no-store, must-revalidate, max-age=0
content-security-policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
date: Sat, 09 Jan 2021 16:28:41 GMT
location: https://my.domain.com/cloud/index.php/apps/oidc_login/oidc?state=51fd9f8fd5483e8c831916b8846c659a&session_state=c5d4065d-df1f-4320-b2ea-c3c4fd9bb861&code=b9fcac41-2ff9-42af-b41e-dee78f9cfa24.c5d4065d-df1f-4320-b2ea-c3c4fd9bb861.5320b6e3-7ebd-4014-9363-4f8d3873365c
p3p: CP="This is not a P3P policy!"
referrer-policy: no-referrer
set-cookie: KEYCLOAK_LOCALE=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/myrealm/; HttpOnly
KC_RESTART=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/myrealm/; HttpOnly
KEYCLOAK_IDENTITY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzY2EzNGNkMC05MTVmLTQzMjItYmIzZi1mYjdkZjllZDQ2NmYifQ.eyJleHAiOjE2MTAyNDU3MjEsImlhdCI6MTYxMDIwOTcyMSwianRpIjoiMTY2N2VjYjQtYmRiNi00NTBkLWEzNDItZmVkYTA4NDE0NTg1IiwiaXNzIjoiaHR0cHM6Ly9vYy44cGF3ZXhwcmVzcy5jb20vYXV0aC9yZWFsbXMvOHBhdyIsInN1YiI6ImQ1ZDk2NmY3LWJhNjAtNGZiMi1hM2ExLTllYTgwZGYzY2FhOSIsInR5cCI6IlNlcmlhbGl6ZWQtSUQiLCJzZXNzaW9uX3N0YXRlIjoiYzVkNDA2NWQtZGYxZi00MzIwLWIyZWEtYzNjNGZkOWJiODYxIiwic3RhdGVfY2hlY2tlciI6Ijk2TTNDMk9rUUV3NS1KeFJOMTl3TjdPVnNEVEVvc01kZm5TeHFfQkJiQ0EifQ.Nrb-Mul7PunCMp-YX6NkjLTReLMoaEg5JOj8AdiEH3I; Version=1; Path=/auth/realms/myrealm/; SameSite=None; Secure; HttpOnly
KEYCLOAK_IDENTITY_LEGACY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzY2EzNGNkMC05MTVmLTQzMjItYmIzZi1mYjdkZjllZDQ2NmYifQ.eyJleHAiOjE2MTAyNDU3MjEsImlhdCI6MTYxMDIwOTcyMSwianRpIjoiMTY2N2VjYjQtYmRiNi00NTBkLWEzNDItZmVkYTA4NDE0NTg1IiwiaXNzIjoiaHR0cHM6Ly9vYy44cGF3ZXhwcmVzcy5jb20vYXV0aC9yZWFsbXMvOHBhdyIsInN1YiI6ImQ1ZDk2NmY3LWJhNjAtNGZiMi1hM2ExLTllYTgwZGYzY2FhOSIsInR5cCI6IlNlcmlhbGl6ZWQtSUQiLCJzZXNzaW9uX3N0YXRlIjoiYzVkNDA2NWQtZGYxZi00MzIwLWIyZWEtYzNjNGZkOWJiODYxIiwic3RhdGVfY2hlY2tlciI6Ijk2TTNDMk9rUUV3NS1KeFJOMTl3TjdPVnNEVEVvc01kZm5TeHFfQkJiQ0EifQ.Nrb-Mul7PunCMp-YX6NkjLTReLMoaEg5JOj8AdiEH3I; Version=1; Path=/auth/realms/myrealm/; HttpOnly
KEYCLOAK_SESSION=myrealm/d5d966f7-ba60-4fb2-a3a1-9ea80df3caa9/c5d4065d-df1f-4320-b2ea-c3c4fd9bb861; Version=1; Expires=Sun, 10-Jan-2021 02:28:41 GMT; Max-Age=36000; Path=/auth/realms/myrealm/; SameSite=None; Secure
KEYCLOAK_SESSION_LEGACY=myrealm/d5d966f7-ba60-4fb2-a3a1-9ea80df3caa9/c5d4065d-df1f-4320-b2ea-c3c4fd9bb861; Version=1; Expires=Sun, 10-Jan-2021 02:28:41 GMT; Max-Age=36000; Path=/auth/realms/myrealm/
KEYCLOAK_REMEMBER_ME=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/myrealm/; HttpOnly
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-robots-tag: none
x-xss-protection: 1; mode=block
content-length: 0
X-Firefox-Spdy: h2
```

</details>

<details><summary> <code>/cloud/index.php/apps/oidc_login/oidc</code> </summary>

```
await fetch("https://my.domain.com/cloud/index.php/apps/oidc_login/oidc?state=51fd9f8fd5483e8c831916b8846c659a&session_state=c5d4065d-df1f-4320-b2ea-c3c4fd9bb861&code=b9fcac41-2ff9-42af-b41e-dee78f9cfa24.c5d4065d-df1f-4320-b2ea-c3c4fd9bb861.5320b6e3-7ebd-4014-9363-4f8d3873365c", {
    "credentials": "include",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Upgrade-Insecure-Requests": "1",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    },
    "method": "GET",
    "mode": "cors"
});

GET /cloud/index.php/apps/oidc_login/oidc?state=51fd9f8fd5483e8c831916b8846c659a&session_state=c5d4065d-df1f-4320-b2ea-c3c4fd9bb861&code=b9fcac41-2ff9-42af-b41e-dee78f9cfa24.c5d4065d-df1f-4320-b2ea-c3c4fd9bb861.5320b6e3-7ebd-4014-9363-4f8d3873365c HTTP/1.1
Host: my.domain.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Cookie: 50d74b05873f4=f0c01464dddfa0f27baa85ea165aeafd; oc_sessionPassphrase=hMZb4IWamGUNYjFTaYxl%2BEM7EDmAh8IAopuK0jHni3mXEG7N4IqCmE0y9jee5T8xsxPzuZ%2F5do1HuVe8bvUvuUoQviN7494r2MqS7kncyXEdwhuKlUicyoeWVyQKxvxY; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache

HTTP/2 302 Found
cache-control: no-store, no-cache, must-revalidate
content-security-policy: default-src 'self'; script-src 'self' 'nonce-a0NISUNPRkxHV1I1K1NRd3dlc0QzSzU2aFY5eFgzdTZjOXBmdjdjQWtGUT06M1JDaVJzb3ZlQTByMWwxZDdvZFd2dWNqempWQkNpUDlOck1VOW9WanhHVT0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
content-type: text/html; charset=UTF-8
date: Sat, 09 Jan 2021 16:28:41 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
location: https://my.domain.com/cloud/index.php/login?noredir=1
pragma: no-cache
referrer-policy: no-referrer
server: Apache/2.4.38 (Debian)
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-powered-by: PHP/7.4.11
x-robots-tag: none
x-xss-protection: 1; mode=block
content-length: 0
X-Firefox-Spdy: h2
```

</details>

<details><summary> <code>/cloud/index.php/login?noredir=1</code> </summary>

```
await fetch("https://my.domain.com/cloud/index.php/login?noredir=1", {
    "credentials": "include",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Upgrade-Insecure-Requests": "1",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    },
    "method": "GET",
    "mode": "cors"
});

GET /cloud/index.php/login?noredir=1 HTTP/1.1
Host: my.domain.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Cookie: 50d74b05873f4=f0c01464dddfa0f27baa85ea165aeafd; oc_sessionPassphrase=hMZb4IWamGUNYjFTaYxl%2BEM7EDmAh8IAopuK0jHni3mXEG7N4IqCmE0y9jee5T8xsxPzuZ%2F5do1HuVe8bvUvuUoQviN7494r2MqS7kncyXEdwhuKlUicyoeWVyQKxvxY; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache

HTTP/2 200 OK
cache-control: no-cache, no-store, must-revalidate
content-encoding: gzip
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-MzFkR3NnRnlUaTdQa0thYTFqZkUwWDhhVHZUS1Jaa2lCRzhxNVhuSVJSMD06a21Zcy9Db1dMMGVkdjkvMytWdVJzelpEQlo3NkVNRmxRUVpockV1ckVTdz0=';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self' data:;connect-src 'self';media-src 'self';frame-ancestors 'self';worker-src 'self' blob:;form-action 'self'
content-type: text/html; charset=UTF-8
date: Sat, 09 Jan 2021 16:28:41 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
feature-policy: autoplay 'self';camera 'none';fullscreen 'self';geolocation 'none';microphone 'none';payment 'none'
pragma: no-cache
referrer-policy: no-referrer
server: Apache/2.4.38 (Debian)
vary: Accept-Encoding
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-powered-by: PHP/7.4.11
x-robots-tag: none
x-xss-protection: 1; mode=block
content-length: 3846
X-Firefox-Spdy: h2
```

</details>
