### ISSUE TITLE
The provider authorization_endpoint could not be fetched

### ISSUE THREAD

**Issue by King-Cole** [pulsejet/nextcloud-oidc-login#235]
Hi All,

I'm trying to get my Authelia instance to play nice with Nextcloud using this wonderful creation, but despite pouring over my configs for the last several hours, cannot get Nextcloud to reach Authelia, instead getting an error message "The provider authorization_endpoint could not be fetched. Make sure your provider has a well known configuration available."

I am running both Nextcloud and Authelia in docker containers, all behind an Nginx proxy (which I suspect might be the issue).

Here is my config for Nextcloud:
```
  'allow_user_to_change_display_name' => false,
  'lost_password_link' => 'disabled',
  'overwriteprotocol' => 'https',
  'allow_local_remote_servers' => true,
  'oidc_login_provider_url' => 'https://auth.<myinstance>.com',
  'oidc_login_client_id' => 'nextcloud',
  'oidc_login_client_secret' => '$goodsecret',
  'oidc_login_auto_redirect' => false,
  'oidc_login_end_session_redirect' => false,
  'oidc_login_button_text' => 'Log in with Authelia',
  'oidc_login_hide_password_form' => false,
  'oidc_login_use_id_token' => true,
  'oidc_login_attributes' => 
  array (
    'id' => 'sub',
    'name' => 'name',
    'mail' => 'email',
    'groups' => 'groups',
  ),
  'oidc_login_default_group' => 'oidc',
  'oidc_login_use_external_storage' => false,
  'oidc_login_scope' => 'openid profile email groups',
  'oidc_login_proxy_ldap' => false,
  'oidc_login_disable_registration' => true,
  'oidc_login_redir_fallback' => false,
  'oidc_login_alt_login_page' => 'assets/login.php',
  'oidc_login_tls_verify' => true,
  'oidc_create_groups' => false,
  'oidc_login_webdav_enabled' => false,
  'oidc_login_password_authentication' => false,
  'oidc_login_public_key_caching_time' => 86400,
  'oidc_login_min_time_between_jwks_requests' => 10,
  'oidc_login_well_known_caching_time' => 86400,
  'oidc_login_update_avatar' => false,
```

And the config in Authelia:
```
identity_providers:
  oidc:
    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    hmac_secret: $goodsecret
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      <snip>
      -----END RSA PRIVATE KEY-----
    clients:
    - id: nextcloud
      description: NextCloud
      secret: '$goodsecret'
      public: false
      authorization_policy: two_factor
      redirect_uris:
        - https://cloud.<myinstance>.com/apps/oidc_login/oidc
        - https://openidconnect.net/callback
        - https://oidcdebugger.com/debug
      scopes:
        - openid
        - profile
        - email
        - groups
      userinfo_signing_algorithm: none
```
As you can tell from my redirect_uris I used both openidconnect.net and oidcdebugger.com to test the Authelia side of things, and it all appears working fine. Any ideas? My only thought is that it has to be the reverse proxy not playing nice with Nextcloud as it appears from the logs that it's never reaching Authelia in the first place.
