### ISSUE TITLE
Help with configuration for DAV with authelia

### ISSUE THREAD

**Issue by aleprovencio** [pulsejet/nextcloud-oidc-login#250]
Hi!

I have already managed to make this app to work to `authelia`, so logging in is just a matter of clicking `Log in with authelia` button on `nextcloud`'s `WebUI` login page.

However, I'm having a hard time trying to make `nextcloud`'s clients (`webdav`, `caldav`, `carddav`) to authenticate by the means of `app tokens` generated on `nextcloud`'s admin settings.

Do I have to mess with [access control rules](https://www.authelia.com/configuration/security/access-control/) bypassing the used resources, or can `OIDC` take care of it? I have tried set `oidc_login_webdav_enabled` to `true` but it does not work yet, so I must be missing something.

My config files were based off [this example](https://www.authelia.com/integration/openid-connect/nextcloud/), and I have posted the relevant parts bellow.

Can you please help?

`authelia`
``` yaml

identity_providers:
  oidc:
    hmac_secret: '{{ authelia_hmac_secret }}'
    issuer_private_key: |
      {{ authelia_issuer_private_key }}
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - "*"
        # - https://{{ domain_name }}
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: nextcloud
        description: NextCloud
        secret: '{{ authelia_nextcloud_secret }}'
        public: false
        authorization_policy: two_factor
        consent_mode: implicit
        redirect_uris:
          - https://nextcloud.{{ domain_name }}/apps/oidc_login/oidc
        scopes:
          - openid
          - profile
          - email
          - groups
        userinfo_signing_algorithm: none
```

`nextcloud`
``` php
  'allow_user_to_change_display_name' => false,
  'lost_password_link' => 'disabled',
  'oidc_login_provider_url' => 'https://authelia.{{ domain_name }}',
  'oidc_login_client_id' => 'nextcloud',
  'oidc_login_client_secret' => {{ stack_apps_nextcloud_oidc_login_client_secret }},
  'oidc_login_auto_redirect' => false,
  'oidc_login_end_session_redirect' => false,
  'oidc_login_button_text' => 'Log in with Authelia',
  'oidc_login_hide_password_form' => false,
  'oidc_login_use_id_token' => true,
  'oidc_login_attributes' => array (
      'id' => 'preferred_username',
      'name' => 'name',
      'mail' => 'email',
      'groups' => 'groups',
      'is_admin' => true,
  ),
  'oidc_login_default_group' => 'oidc',
  'oidc_login_use_external_storage' => false,
  'oidc_login_scope' => 'openid profile email groups',
  'oidc_login_proxy_ldap' => false,
  'oidc_login_disable_registration' => true,
  'oidc_login_redir_fallback' => false,
  'oidc_login_alt_login_page' => 'assets/login.php',
  'oidc_login_tls_verify' => true,
  'oidc_create_groups' => false,
  'oidc_login_webdav_enabled' => true,
  'oidc_login_password_authentication' => false,
  'oidc_login_public_key_caching_time' => 86400,
  'oidc_login_min_time_between_jwks_requests' => 10,
  'oidc_login_well_known_caching_time' => 86400,
  'oidc_login_update_avatar' => false,
```

**Comment by linuxluser** [comment]
I had issues with the "Memories" client app on Android. It uses the [login flow V2](https://docs.nextcloud.com/server/stable/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2) outlined by Nextcloud. Essentially, uses the browser to login and takes authentication from there.

For me, the only resource exclusion patterns I needed were:

```
access_control:
  rules:
    - domain: authelia.{{ domain_name }}
      policy: bypass
    - domain: nextcloud.{{ domain_name }}
      resources:
        - '^\/(index.php\/)?login\/v2'  # NC login V2 flow
        - '^\/(index.php\/)?apps\/memories\/'  # Memories Android app
      policy: bypass
    - domain: nextcloud.{{ domain_name }}
      policy: two_factor
```

Note that I didn't use `$` at the end of the pattern, thus allowing ANY URLs that start with those two. This seemed necessary but for anyone who wants to spend the effort to get the complete list of /login/v2/... URLs, go ahead.

It kind of sucks to have to expose some Nextcloud endpoints like this but I don't think there's any way around it. Furthermore, it seems that you need to test on a per-app basis to ensure that if the app needs to query specific URLs from the Nextcloud instance that are meant to be public that you have those in your list as well. Kind of a pain, TBH.
