### ISSUE TITLE
login error "Can not get identifier from provider"

### ISSUE THREAD

**Issue by schklom** [pulsejet/nextcloud-oidc-login#311]
When logging with Authelia recently, I get the error `Can not get identifier from provider`.

My config is
```php
  'oidc_login_provider_url' => 'https://authelia.mydomain.com',
  'oidc_login_client_id' => 'nextcloud',
  'oidc_login_client_secret' => 'XXXXX',
  'oidc_login_auto_redirect' => false,
  'oidc_login_end_session_redirect' => false,
  'oidc_login_button_text' => 'Log in with Authelia',
  'oidc_login_hide_password_form' => false,
  'oidc_login_use_id_token' => true,
  'oidc_login_attributes' => 
  array (
    'id' => 'preferred_username',
    'name' => 'name',
    'mail' => 'email',
    'groups' => 'groups',
  ),
  'oidc_login_default_group' => 'oidc',
  'oidc_login_use_external_storage' => false,
  'oidc_login_scope' => 'openid profile email groups',
  'oidc_login_proxy_ldap' => false,
  'oidc_login_disable_registration' => false,
  'oidc_login_redir_fallback' => false,
  'oidc_login_tls_verify' => true,
  'oidc_create_groups' => true,
  'oidc_login_webdav_enabled' => false,
  'oidc_login_password_authentication' => false,
  'oidc_login_public_key_caching_time' => 86400,
  'oidc_login_min_time_between_jwks_requests' => 10,
  'oidc_login_well_known_caching_time' => 86400,
  'oidc_login_update_avatar' => false,
  'oidc_login_code_challenge_method' => 'S256'
```
and Authelia's config similar to https://www.authelia.com/integration/openid-connect/nextcloud/#authelia-1
```yaml
      - client_id: nextcloud
        client_name: NextCloud
        client_secret: '$pbkdf2-XXXXX'
        public: false
        authorization_policy: two_factor
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://nextcloud.mydomain.com/apps/oidc_login/oidc'
        scopes:
          - openid
          - profile
          - email
          - groups
        userinfo_signed_response_alg: none
        pre_configured_consent_duration: '1 week'
        token_endpoint_auth_method: 'client_secret_basic'
```
I recently updated Nextcloud to 30.0.8.1.

OIDC login works well with other services, so I think the problem is here, but I could be wrong.
